---
repos:
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - name: Generate Markdown Table of Contents
        id: doctoc
        args:
          - --github
          - --update-only

  - repo: local
    hooks:
      - id: update-todo-md
        name: Update TODO.md
        entry: scripts/update-todos.sh
        language: system
        pass_filenames: false

  - repo: https://github.com/DevinR528/cargo-sort
    rev: v2.0.2
    hooks:
      - name: Sort dependencies alphabetically
        id: cargo-sort
        args:
          - --workspace
        files: \.toml$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: just fmt
        language: system
        files: \.rs$
        pass_filenames: false
      - id: clippy
        name: clippy
        description: Check if all files implement Clippy lints
        entry: just lint
        language: system
        files: \.rs$
        pass_filenames: false
