[package]
name = "uefi-loader"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
uefi = { workspace = true, features = ["panic_handler"] }