[build]
# This target specification is only effective when building from this directory.
# For builds from the workspace, the triple needs to be specified
# explicitly per package.
#
# See the workspace-level .cargo/config.toml for build aliases.
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
linker = "rust-lld"
rustflags = [
    "-Crelocation-model=static",
    "-Cpanic=abort",
]
