name: Build UEFI (os/uefi)

on:
  push:
    branches: [ main ]
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'os/uefi/**'
      - 'os/kernel/kernel-info/**'
      - 'os/kernel/kernel-qemu/**'
      - 'os/kernel/kernel-vmem/**'
      - '.github/workflows/build-uefi.yaml'
  pull_request:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'os/uefi/**'
      - 'os/kernel/kernel-info/**'
      - 'os/kernel/kernel-qemu/**'
      - 'os/kernel/kernel-vmem/**'
      - '.github/workflows/build-uefi.yaml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-unknown-uefi

      - name: Cache build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            os/uefi -> target

      - name: Build (release)
        run: cargo build --release --target x86_64-unknown-uefi
        working-directory: os/uefi/uefi-loader

      - name: Package and hash (compress → sha256)
        run: |
          BIN=target/x86_64-unknown-uefi/release/uefi-loader.efi
          OUT=uefi-loader.tar.gz
          tar -czf "$OUT" -C "$(dirname "$BIN")" "$(basename "$BIN")"
          sha256sum "$OUT" | tee "$OUT.sha256"
          echo "Archive + hash:"
          ls -lh "$OUT" "$OUT.sha256"
          cat "$OUT.sha256"

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: uefi-loader-release
          path: |
            uefi-loader.tar.gz
            uefi-loader.tar.gz.sha256
          retention-days: 14
