name: Build Kernel (os/kernel)

on:
  push:
    branches: [ main ]
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'os/kernel/**'
      - '.github/workflows/build-kernel.yaml'
  pull_request:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'os/kernel/**'
      - '.github/workflows/build-kernel.yaml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: os/kernel/kernel

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-unknown-none

      - name: Cache build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            os/kernel -> target

      - name: Build (release)
        run: cargo build --release --target x86_64-unknown-none
