name: Deploy Rust Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'os/**'
      - '.github/workflows/gh-pages.yaml'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Build Rust Documentation
        # run: cargo doc --workspace --document-private-items --no-deps
        env:
          RUSTDOCFLAGS: --enable-index-page -Zunstable-options
        run: cargo +nightly doc --workspace --document-private-items --no-deps

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          force_orphan: true
